MainApp/urls.py
from django.conf.urls import patterns, url
from MainApp import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index')
)

simansur/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from MainApp import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'simansur.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', views.user_login, name='login'),
    url(r'^accounts/logout/$', views.user_logout, name='logout'),

    url(r'^surat/$', views.surat, name='surat'),
    url(r'^surat/(?P<no_surat>[\w]+)/$', views.surat_detail, name='surat_detail'), # look for any sequence of alphanumeric characters (e.g. a-z, A-Z, or 0-9)
    url(r'^surat_tambah/$', views.surat_tambah, name='surat_tambah'),
    url(r'^surat_edit/(?P<no_surat>[\w]+)/$', views.surat_edit, name='surat_edit'),
    url(r'^surat_delete/(?P<no_surat>[\w]+)/$', views.surat_delete, name='surat_delete'),
    url(r'^surat_download/(?P<no_surat>[\w]+)/$', views.surat_download, name='surat_download'),
    url(r'^surat_kirim/(?P<no_surat>[\w]+)/$', views.surat_kirim, name='surat_kirim'),

    url(r'^track_surat/(?P<no_surat>[\w]+)/$', views.track_surat, name='track_surat'),


    url(r'^surat_pengguna/$', views.surat_pengguna, name='surat_pengguna'),
    url(r'^surat_pengguna_detail/(?P<id>[\w]+)/$', views.surat_pengguna_detail, name='surat_pengguna_detail'),
    url(r'^surat_pengguna_disposisi/(?P<id>[\w]+)/$', views.surat_pengguna_disposisi, name='surat_pengguna_disposisi'),

    url(r'^user/$', views.user, name='user'),
    url(r'^user/(?P<username>[\w\-]+)/$', views.user_detail, name='user_detail'),
    url(r'^user_tambah/$', views.user_tambah, name='user_tambah'),
    url(r'^user_edit/(?P<username>[\w\-]+)/$', views.user_edit, name='user_edit'),
    url(r'^user_delete/(?P<username>[\w\-]+)/$', views.user_delete, name='user_delete'),

    url(r'^aktivitas/$', views.aktivitas, name='aktivitas'),

    url(r'^statistik/$', views.statistik, name='statistik'),


)

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    bidang = models.CharField(max_length=40, default="")
    jabatan = models.CharField(max_length=40, default="")
    no_telepon = models.CharField(max_length=15, default="")

    #def __unicode__(self): #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.user.username


class Surat(models.Model):
    no_surat = models.CharField(null=False, unique=True, max_length=15)
    no_agenda = models.CharField(null=False, max_length=15)
    perihal = models.TextField(null=True)
    tanggal_surat_masuk = models.DateField(null=True, auto_now_add=False)
    pengirim_surat_fisik = models.TextField(null=True)
    tingkat_kepentingan = models.CharField(null=True, max_length=15)
    file_surat = models.FileField(upload_to=settings.UPLOAD_PATH, null=True, blank=True)
    pencatat = models.ForeignKey(User, null=True, related_name='pencatat_surat')
    tanggal_pencatatan = models.DateTimeField(null=True,auto_now_add=True)
    status = models.CharField(null=True, max_length=15) # dilabeli, dikirim, dihapus

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.no_surat

# berisi semua surat untuk masing-masing user
class KotakSurat(models.Model):
    id = models.AutoField(primary_key=True)
    surat = models.ForeignKey(Surat, null=False, related_name='surat_kotak_surat')
    pengirim = models.ForeignKey(User, null=True, related_name='pengirim_kotak_surat')
    penerima = models.ForeignKey(User, null=True, related_name='penerima_kotak_surat')
    status = models.CharField(null=True, max_length=15) # diterima, dibaca, didisposisi
    catatan_tambahan = models.TextField(null=True)
    jenis_pengiriman = models.CharField(null=False, max_length=15) # langsung, disposisi
    tanggal = models.DateTimeField(auto_now_add=True)

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.no_surat

class Aktivitas(models.Model):
    id = models.AutoField(primary_key=True)
    tanggal = models.DateTimeField(null=False,auto_now_add=True)
    user = models.ForeignKey(User, null=False, related_name='user_aktivitas')
    aktivitas = models.CharField(null=False, max_length=255)

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.aktivitas

class TrackSurat(models.Model):
    id = models.AutoField(primary_key=True)
    surat = models.ForeignKey(Surat, null=False, related_name='surat_track_surat')
    tanggal = models.DateTimeField(null=False,auto_now_add=True)
    status = models.CharField(null=False, max_length=255)

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.status

MainApp/views.py
import  os, json, urllib
import urllib.request as urllib2

from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group, Permission
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from MainApp.models import Surat, Disposisi, UserProfile, Aktivitas, TrackSurat, KotakSurat
from MainApp.forms import SuratForm, DisposisiForm, UserProfileForm, KirimSuratForm, StatistikForm, CariSuratForm

# konfigurasi tambahan
DATA_PER_HALAMAN = 2 # untuk pagination
INTEGRASI_LDAP = False # False = integrasi tidak aktiv, True = integrasi aktiv.

# untuk mengecek apakah user termasuk dalam kelompok groups yang diijinkan untuk mengakses methods pada view
# user akan langsung diarahkan ke form login jika tidak memiliki hak akses tanpa pesan apapun jika menggunakan method ini.
"""
def group_required(*group_names):
    #Requires user membership in at least one of the groups passed in
    def in_groups(u):
        if u.is_authenticated():
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False
    return user_passes_test(in_groups, login_url='/login')
"""

def index(request):
    context_dict = {'slug': 'login', 'page_home_active':'active'}

    return render(request, 'MainApp/index.html', context_dict)

@login_required
def surat(request):
    # data untuk di tampilkan di template
    data = {}

    # user yang sedang login
    user_saat_ini = request.user

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        form = CariSuratForm(request.POST, empty_permitted=True)
        data['form'] = form
        kata_kunci = None

        # Have we been provided with a valid form?
        if form.is_valid():
            data_form = form.cleaned_data

            if data_form.get('kata_kunci') != "":
                kata_kunci = data_form.get('kata_kunci')

        else:
            print(form.errors)

    else:
        kata_kunci = None

        form = CariSuratForm(empty_permitted=True)
        data['form'] = form

    # ambil data surat sesuai dengan yang login
    if user_dalam_group(user_saat_ini, 'manajer') | user_saat_ini.is_superuser:

        try:
            # manajer surat atau superadmin akan bisa mendapatkan semua data surat
            if kata_kunci == None :
                semua_surat = Surat.objects.all().order_by('-tanggal_surat_masuk')
            else:
                semua_surat = Surat.objects.filter(Q(no_surat__contains=kata_kunci) | Q(perihal__contains=kata_kunci)).order_by('-tanggal_surat_masuk')

        except Surat.DoesNotExist:
            semua_surat = None


    else:
        # selain admin atau manajer hanya akan mendapatkan data surat yang ditujukan atau di dikirim olehnya
        try:
            # ambil semua surat yang terkait dengan user saja
            # user terkait yaitu, pengirim surat, penerima surat, dan penerima disposisi
            if kata_kunci == None :
                semua_surat = Surat.objects.filter(pencatat=user_saat_ini).order_by('-tanggal_surat_masuk')
            else:
                semua_surat = Surat.objects.filter(pencatat=user_saat_ini)\
                    .filter(Q(no_surat__contains=kata_kunci) | Q(perihal__contains=kata_kunci))\
                    .order_by('-tanggal_surat_masuk')

        except Surat.DoesNotExist:
            semua_surat = None

    # pagination untuk surat (label surat)
    paginator = Paginator(semua_surat, DATA_PER_HALAMAN)

    page = request.GET.get('page')
    try:
        label_surat = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        label_surat = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        label_surat = paginator.page(paginator.num_pages)

    jumlah_data_sebelumnya  = (label_surat.number - 1) * DATA_PER_HALAMAN

    data['semua_surat'] = label_surat
    data['jumlah_data_sebelumnya'] = jumlah_data_sebelumnya
    data['page_surat_active'] = 'active'


    return render(request, 'MainApp/surat/surat.html', data)

@login_required
def surat_detail(request, no_surat):

    # get data surat
    dataSurat = Surat.objects.get(no_surat=no_surat)

    try:
        # get disposisi surat
        semua_disposisi_surat = Disposisi.objects.filter(surat=dataSurat)

    except Disposisi.DoesNotExist:
         semua_disposisi_surat = None

    context_dict = {'surat': dataSurat, 'semua_disposisi_surat': semua_disposisi_surat, 'page_surat_active':'active'}

    return render(request, 'MainApp/surat/surat_detail.html', context_dict)

@login_required
def surat_delete(request, no_surat):
    data = {}

    user_saat_ini = request.user

    # Hanya user yang memiliki hak akses untuk menghapus surat diperbolehkan untuk menghapus label surat
    if user_saat_ini.has_perm('MainApp.delete_surat') == False :
        data['alert_type'] =  "danger"
        data['alert_message'] = "Anda tidak di ijinkan untuk menghapus label surat!"
        return render(request, "MainApp/index.html", data)

    try:
        # get data surat
        dataSurat = Surat.objects.get(no_surat=no_surat)

        # hanya surat yang belum dikirim atau didisposisi yang bisa dihapus
        if dataSurat.status != "dilabeli":
            data['alert_type'] =  "danger"
            data['alert_message'] = "Hanya surat yang belum dikirimkan atau didisposisikan yang bisa dihapus!"
            return render(request, "MainApp/index.html", data)

        dataSurat.delete()

    except Surat.DoesNotExist:
        # jika data surat yang diinginkan untuk dihapus tidak ditemukan, tampilkan daftar semua surat
        return surat(request)

    # get data surat
    semua_surat = Surat.objects.all()

    context_dict = {'semua_surat': semua_surat, 'page_surat_active':'active'}

    return render(request, 'MainApp/surat/surat.html', context_dict)

@login_required
#@group_required('admin', 'pencatat surat')
# tambah surat artinya melabeli surat baru, belum mengirimkannya.
def surat_tambah(request):
    data = {}

    # dapatkan data user yang sedang login
    user_saat_ini = request.user
    
    # Hanya user yang memiliki hak akses untuk menambah surat diperbolehkan untuk melabeli surat baru
    if user_saat_ini.has_perm('MainApp.add_surat') == False :
        data['alert_type'] =  "danger"
        data['alert_message'] = "Anda tidak di ijinkan untuk menambah label surat baru!"
        return render(request, "MainApp/index.html", data)

    # A HTTP POST?
    if request.method == 'POST':
        form = SuratForm(request.POST, request.FILES)

        # Have we been provided with a valid form?
        if form.is_valid():
            data_surat = form.save(commit=False)

            data_surat.pencatat = user_saat_ini
            data_surat.status = "dilabeli"
            form.save(commit=True)

            # kembali ke halaman daftar surat
            return HttpResponseRedirect('/surat/')
        else:
            # The supplied form contained errors - just print them to the terminal.
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = SuratForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'MainApp/surat/surat_tambah.html', {'form': form, 'page_surat_active':'active'})

@login_required
def surat_edit(request, no_surat):

    # get data surat
    dataSurat = Surat.objects.get(no_surat=no_surat)

    # A HTTP POST?
    if request.method == 'POST':
        form = SuratForm(request.POST, request.FILES, instance=dataSurat)

        # Have we been provided with a valid form?
        if form.is_valid():

            form.save(commit=True)

            # go to surat view
            return surat(request)

        else:
            # The supplied form contained errors - just print them to the terminal.
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = SuratForm(instance=dataSurat)

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'MainApp/surat/surat_edit.html', {'form': form ,'no_surat': no_surat, 'page_surat_active':'active'})

@login_required
def surat_download(request, no_surat):

    try:

        # get data surat
        dataSurat = Surat.objects.get(no_surat=no_surat)
        file = dataSurat.file_surat
        nama_file = os.path.basename(file.url)

        response = HttpResponse(file, content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename=%s' % nama_file

        #response['X-Sendfile'] = smart_str(file)

        return response

    except Surat.DoesNotExist:

        # jika data surat yang diinginkan untuk dihapus tidak ditemukan, tampilkan daftar semua surat
        return surat_detail(request, no_surat)

@login_required
def surat_kirim(request, no_surat):
    data = {}

    user_saat_ini = request.user

    # get data surat
    data_surat = Surat.objects.get(no_surat=no_surat)

    # A HTTP POST?
    if request.method == 'POST':
        form = KirimSuratForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():

            data_form = form.cleaned_data

            # tambahkan data kotak surat untuk user penerima
            kotak_surat = KotakSurat()
            kotak_surat.surat = data_surat
            kotak_surat.catatan_tambahan = data_form.get('catatan_tambahan')

templates/MainApp/surat/surat.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ slug|capfirst }}{% endblock %}

{% block body-id %}{{ slug|slugify }}{% endblock %}

{% block content%}
        <div class="page-header">
            <h1>Form Pencarian Label Surat</h1>
        </div>

        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal" role="form" id="cari_surat_form" method="post" action="/surat/">

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}

                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.help_text }}

                        <label class="control-label col-sm-2">{{ field.label }} </label>
                        <span> {{ field }} </span>
                        <span><input type="submit" name="submit" value="Cari Surat" /></span>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-sm-2">&nbsp;</div>
                        <span>Tips: Kosongkan kata kunci untuk mencari semua surat. Kata kunci diambil dari nomor surat atau perihal.</span>
                    </div>
                {% endfor %}

                </form>
            </div>
        </div>

        <div class="row page-header">
            <div class="col-md-10">
                <h1>Daftar Label Surat</h1>
            </div>

            {% if perms.MainApp.add_surat %}
            <div class="col-md-2">
                <h1>
                    <a href="{% url 'surat_tambah' %}">
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"> Label Surat</span>
                        </button>
                    </a>
                </h1>
            </div>
            {% endif %}
        </div>

        <div class="row">
            <div class="col-md-12">

                {% if semua_surat %}

              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Tanggal Surat</th>
                    <th>No Surat</th>
                    <th>No Agenda</th>
                    <th>Perihal</th>
                    <th>Pengirim</th>
                    <th>Tingkat Kepentingan</th>
                    <th>Status Surat</th>
                    <th>Aksi


                    </th>
                  </tr>
                </thead>
                <tbody>

                {% for surat in semua_surat %}

                  <tr>
                    <td>{{ forloop.counter|add:jumlah_data_sebelumnya }}</td>
                    <td>{{ surat.tanggal_surat_masuk }}</td>
                    <td>{{ surat.no_surat }}</td>
                    <td>{{ surat.no_agenda }}</td>
                    <td>{{ surat.perihal }}</td>
                    <td>{{ surat.pengirim_surat_fisik }}</td>
                    <td>{{ surat.tingkat_kepentingan }}</td>
                    <td>{{ surat.status }}</td>
                    <td>
                        <a href="/surat/{{ surat.no_surat }}">
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-folder-open" aria-hidden="true"></span>
                        </button>
                        </a>

                        {% if perms.MainApp.change_surat and surat.status == 'dilabeli' %}
                        <a href="/surat_edit/{{ surat.no_surat }}">
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </button>
                        </a>
                        {% endif %}

                        {% if perms.MainApp.delete_surat and surat.status == 'dilabeli' %}
                        <a href="/surat_delete/{{ surat.no_surat }}" onclick="return confirm('Apakah anda yakin ingin menghapus surat no {{ surat.no_surat }} ?');">
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-minus" aria-hidden="true"></span>
                        </button>
                        </a>
                        {% endif %}

                        {% if surat.status == 'dilabeli' %}
                        <a href="/surat_kirim/{{ surat.no_surat }}" >
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-envelope" aria-hidden="true"></span>
                        </button>
                        </a>
                        {% endif %}

                        {% if surat.status != 'dilabeli' %}
                        <a href="/track_surat/{{ surat.no_surat }}/" >
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-share" aria-hidden="true"></span>
                        </button>
                        </a>
                        {% endif %}

                    </td>
                  </tr>

                  {% endfor %}

                </tbody>
              </table>

              <div class="pagination">
                    <span class="step-links">
                        {% if semua_surat.has_previous %}
                            <a href="?page={{ semua_surat.previous_page_number }}"> Sebelumnya </a>
                        {% endif %}

                        <span class="current">
                            Halaman {{ semua_surat.number }} dari {{ semua_surat.paginator.num_pages }} halaman.
                        </span>

                        {% if semua_surat.has_next %}
                            <a href="?page={{ semua_surat.next_page_number }}"> Berikutnya </a>
                        {% endif %}
                    </span>
              </div>

                {% else %}
                    <p>Tidak ada data label surat.</p>
                    <p>
                        {% if perms.MainApp.add_surat %}
                        <a href="{% url 'surat_tambah' %}">
                        <button type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"> Label Surat Baru</span>
                        </button>
                        </a>
                        {% endif %}
                    </p>
                {% endif %}

            </div>
        </div>





{% endblock %}

templates/MainApp/surat/surat_edit.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ slug|capfirst }}{% endblock %}

{% block body-id %}{{ slug|slugify }}{% endblock %}

{% block content%}
        <div class="page-header">
            <h1>Tambah Surat Baru</h1>
        </div>

        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal" role="form" id="surat_form" method="post" action="/surat_edit/{{ no_surat }}/" enctype="multipart/form-data">

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}

                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.help_text }}
                        <label class="control-label col-sm-2">{{ field.label }} </label>
                        <div class="col-sm-10"> {{ field }} </div>
                    </div>
                {% endfor %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <input type="submit" name="submit" value="Ubah Surat" />
                </div>
            </div>


        </form>

            </div>
        </div>

        <br /> <br />

{% endblock %}

templates/MainApp/surat/surat_kirim.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }} - {{ slug|capfirst }}{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">

    <style>
	.custom-combobox {
		position: relative;
		display: inline-block;
	}
	.custom-combobox-toggle {
		position: absolute;
		top: 0;
		bottom: 0;
		margin-left: -1px;
		padding: 0;
	}
	.custom-combobox-input {
		margin: 0;
		padding: 5px 10px;
	}
	</style>
{% endblock %}

{% block body-id %}{{ slug|slugify }}{% endblock %}

{% block content%}
        <div class="page-header">
            <h1>Detail Surat</h1>
        </div>

        <div class="row">
            <div class="col-md-12">

                {% if surat %}

              <table class="table">
                <tbody>
                <tr>
                    <td>Tanggal Surat</td>
                    <td>{{ surat.tanggal_surat_masuk }}</td>
                </tr>
                <tr>
                    <td>No Surat</td>
                    <td>{{ surat.no_surat }}</td>
                </tr>
                <tr>
                    <td>No Agenda</td>
                    <td>{{ surat.no_agenda }}</td>
                </tr>
                <tr>
                    <td>Perihal</td>
                    <td>{{ surat.perihal }}</td>
                </tr>
                <tr>
                    <td>Pengirim Surat Fisik</td>
                    <td>{{ surat.pengirim_surat_fisik }}</td>
                </tr>
                <tr>
                    <td>Tingkat Kepentingan</td>
                    <td>{{ surat.tingkat_kepentingan }}</td>
                </tr>
                <tr>
                    <td>Status Surat</td>
                    <td>{{ surat.status }}</td>
                </tr>
                <tr>
                    <td>File Surat</td>
                    <td><a href="{% url 'surat_download' no_surat=surat.no_surat %}">Download</a></td>
                </tr>
                </tbody>
              </table>

                {% else %}
                    <p>Surat yang diminta tidak ditemukan</p>
                {% endif %}

            </div>
        </div>

        <br /> <br />

        <div class="page-header">
            <h2>Form Kirim Surat</h2>
        </div>

        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal" role="form" id="kirim_surat_form" method="post" action="/surat_kirim/{{ no_surat }}/" enctype="multipart/form-data">

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}

                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.help_text }}
                        <label class="control-label col-sm-2">{{ field.label }} </label>
                        <div class="col-sm-10"> {{ field }} </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <input type="submit" name="submit" value="Kirim Surat" />
                    </div>
                </div>

                </form>

            </div>
        </div>

{% endblock %}

{% block js %}

    <script src="{% static 'js/jquery-ui.js' %}"></script>

    <script>
	(function( $ ) {
		$.widget( "custom.combobox", {
			_create: function() {
				this.wrapper = $( "<span>" )
					.addClass( "custom-combobox" )
					.insertAfter( this.element );

				this.element.hide();
				this._createAutocomplete();
				this._createShowAllButton();
			},

			_createAutocomplete: function() {
				var selected = this.element.children( ":selected" ),
					value = selected.val() ? selected.text() : "";

				this.input = $( "<input>" )
					.appendTo( this.wrapper )
					.val( value )
					.attr( "title", "" )
					.addClass( "custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
					.autocomplete({
						delay: 0,
						minLength: 0,
						source: $.proxy( this, "_source" )
					})
					.tooltip({
						tooltipClass: "ui-state-highlight"
					});

				this._on( this.input, {
					autocompleteselect: function( event, ui ) {
						ui.item.option.selected = true;
						this._angger( "select", event, {
							item: ui.item.option
						});
					},

					autocompletechange: "_removeIfInvalid"
				});
			},

			_createShowAllButton: function() {
				var input = this.input,
					wasOpen = false;

				$( "<a>" )
					.attr( "tabIndex", -1 )
					.attr( "title", "Show All Items" )
					.tooltip()
					.appendTo( this.wrapper )
					.button({
						icons: {
							primary: "ui-icon-triangle-1-s"
						},
						text: false
					})
					.removeClass( "ui-corner-all" )
					.addClass( "custom-combobox-toggle ui-corner-right" )
					.mousedown(function() {
						wasOpen = input.autocomplete( "widget" ).is( ":visible" );
					})
					.click(function() {
						input.focus();

						// Close if already visible
						if ( wasOpen ) {
							return;
						}

						// Pass empty string as value to search for, displaying all results
						input.autocomplete( "search", "" );
					});
			},

			_source: function( request, response ) {
				var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
				response( this.element.children( "option" ).map(function() {
					var text = $( this ).text();
					if ( this.value && ( !request.term || matcher.test(text) ) )
						return {
							label: text,
							value: text,
							option: this
						};
				}) );
			},

			_removeIfInvalid: function( event, ui ) {

				// Selected an item, nothing to do
				if ( ui.item ) {
					return;
				}

				// Search for a match (case-insensitive)
				var value = this.input.val(),
					valueLowerCase = value.toLowerCase(),
					valid = false;
				this.element.children( "option" ).each(function() {
					if ( $( this ).text().toLowerCase() === valueLowerCase ) {
						this.selected = valid = true;
						return false;
					}
				});

				// Found a match, nothing to do
				if ( valid ) {
					return;
				}

				// Remove invalid value
				this.input
					.val( "" )
					.attr( "title", value + " didn't match any item" )
					.tooltip( "open" );
				this.element.val( "" );
				this._delay(function() {
					this.input.tooltip( "close" ).attr( "title", "" );
				}, 2500 );
				this.input.autocomplete( "instance" ).term = "";
			},

			_destroy: function() {
				this.wrapper.remove();
				this.element.show();
			}
		});
	})( jQuery );

	$(function() {
		$( "#id_penerima" ).combobox();
	});
	</script>
{% endblock %}

templates/MainApp/surat/surat_tambah.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ slug|capfirst }}{% endblock %}

{% block body-id %}{{ slug|slugify }}{% endblock %}

{% block content%}
        <div class="page-header">
            <h1>Membuat Label Surat Baru</h1>
        </div>

        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal" role="form" id="surat_form" method="post" action="/surat_tambah/" enctype="multipart/form-data">

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}

                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.help_text }}
                        <label class="control-label col-sm-2">{{ field.label }} </label>
                        <div class="col-sm-10"> {{ field }} </div>
                    </div>
                {% endfor %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <input type="submit" name="submit" value="Tambah Surat" />
                </div>
            </div>


        </form>

            </div>
        </div>

        <br /> <br />

{% endblock %}