MainApp/urls.py
from django.conf.urls import patterns, url
from MainApp import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index')
)

simansur/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from MainApp import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'simansur.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', views.user_login, name='login'),
    url(r'^accounts/logout/$', views.user_logout, name='logout'),

    url(r'^surat/$', views.surat, name='surat'),
    url(r'^surat/(?P<no_surat>[\w]+)/$', views.surat_detail, name='surat_detail'), # look for any sequence of alphanumeric characters (e.g. a-z, A-Z, or 0-9)
    url(r'^surat_tambah/$', views.surat_tambah, name='surat_tambah'),
    url(r'^surat_edit/(?P<no_surat>[\w]+)/$', views.surat_edit, name='surat_edit'),
    url(r'^surat_delete/(?P<no_surat>[\w]+)/$', views.surat_delete, name='surat_delete'),
    url(r'^surat_download/(?P<no_surat>[\w]+)/$', views.surat_download, name='surat_download'),
    url(r'^surat_kirim/(?P<no_surat>[\w]+)/$', views.surat_kirim, name='surat_kirim'),

    url(r'^track_surat/(?P<no_surat>[\w]+)/$', views.track_surat, name='track_surat'),


    url(r'^surat_pengguna/$', views.surat_pengguna, name='surat_pengguna'),
    url(r'^surat_pengguna_detail/(?P<id>[\w]+)/$', views.surat_pengguna_detail, name='surat_pengguna_detail'),
    url(r'^surat_pengguna_disposisi/(?P<id>[\w]+)/$', views.surat_pengguna_disposisi, name='surat_pengguna_disposisi'),

    url(r'^user/$', views.user, name='user'),
    url(r'^user/(?P<username>[\w\-]+)/$', views.user_detail, name='user_detail'),
    url(r'^user_tambah/$', views.user_tambah, name='user_tambah'),
    url(r'^user_edit/(?P<username>[\w\-]+)/$', views.user_edit, name='user_edit'),
    url(r'^user_delete/(?P<username>[\w\-]+)/$', views.user_delete, name='user_delete'),

    url(r'^aktivitas/$', views.aktivitas, name='aktivitas'),

    url(r'^statistik/$', views.statistik, name='statistik'),


)

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    bidang = models.CharField(max_length=40, default="")
    jabatan = models.CharField(max_length=40, default="")
    no_telepon = models.CharField(max_length=15, default="")

    #def __unicode__(self): #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.user.username


class Surat(models.Model):
    no_surat = models.CharField(null=False, unique=True, max_length=15)
    no_agenda = models.CharField(null=False, max_length=15)
    perihal = models.TextField(null=True)
    tanggal_surat_masuk = models.DateField(null=True, auto_now_add=False)
    pengirim_surat_fisik = models.TextField(null=True)
    tingkat_kepentingan = models.CharField(null=True, max_length=15)
    file_surat = models.FileField(upload_to=settings.UPLOAD_PATH, null=True, blank=True)
    pencatat = models.ForeignKey(User, null=True, related_name='pencatat_surat')
    tanggal_pencatatan = models.DateTimeField(null=True,auto_now_add=True)
    status = models.CharField(null=True, max_length=15) # dilabeli, dikirim, dihapus

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.no_surat

# berisi semua surat untuk masing-masing user
class KotakSurat(models.Model):
    id = models.AutoField(primary_key=True)
    surat = models.ForeignKey(Surat, null=False, related_name='surat_kotak_surat')
    pengirim = models.ForeignKey(User, null=True, related_name='pengirim_kotak_surat')
    penerima = models.ForeignKey(User, null=True, related_name='penerima_kotak_surat')
    status = models.CharField(null=True, max_length=15) # diterima, dibaca, didisposisi
    catatan_tambahan = models.TextField(null=True)
    jenis_pengiriman = models.CharField(null=False, max_length=15) # langsung, disposisi
    tanggal = models.DateTimeField(auto_now_add=True)

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.no_surat

class Aktivitas(models.Model):
    id = models.AutoField(primary_key=True)
    tanggal = models.DateTimeField(null=False,auto_now_add=True)
    user = models.ForeignKey(User, null=False, related_name='user_aktivitas')
    aktivitas = models.CharField(null=False, max_length=255)

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.aktivitas

class TrackSurat(models.Model):
    id = models.AutoField(primary_key=True)
    surat = models.ForeignKey(Surat, null=False, related_name='surat_track_surat')
    tanggal = models.DateTimeField(null=False,auto_now_add=True)
    status = models.CharField(null=False, max_length=255)

    #def __unicode__(self):  #For Python 2, use __str__ on Python 3
    def __str__(self):
        return self.status

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>{% block title %}SIMANSUR - Sistem Manajemen Surat{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/site.css' %}">
        {% block css %} {% endblock %}
    </head>

    <body role="document" id="{% block body-id %}body{% endblock %}">
        {% block alert %}
            {% if alert_type == "success" %}
                <div class="alert alert-success alert-dismissible text-center" role="alert">
                    {{ alert_message }}
                </div>
            {% elif alert_type == "info" %}
                <div class="alert alert-info alert-dismissible text-center" role="alert">
                    {{ alert_message }}
                </div>
            {% elif alert_type == "warning" %}
                <div class="alert alert-warning alert-dismissible text-center" role="alert">
                    {{ alert_message }}
                </div>
            {% elif alert_type == "danger" %}
                <div class="alert alert-danger alert-dismissible text-center" role="alert">
                    {{ alert_message }}
                </div>
            {% else %}

            {% endif %}
        {% endblock %}

        {% block jumbotron %}
        <div class="page-header text-center">
            <h1>Sistem Manajemen Surat</h1>
        </div>
        {% endblock %}

        {% block nav-wrapper %}
         <!-- Fixed navbar -->
        <nav class="navbar navbar-inverse">
          <div class="container ">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home' %}">SIMANSUR</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="{{ page_home_active }}"><a href="{% url 'home' %}">Home</a></li>

                {% if user.is_authenticated %}
                <li class="{{ page_surat_pengguna_active }}"><a href="{% url 'surat_pengguna' %}">Kotak Masuk</a></li>

                  {% if perms.MainApp.add_surat %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tools <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="{{ page_surat_active }}"><a href="{% url 'surat' %}">Label Surat</a></li>
                    <li class="{{ page_statistic_surat_active }}"><a href="{% url 'statistik' %}">Lihat Statistik</a></li>
                  </ul>
                </li>
                  {% endif %}

                  {% if user.is_superuser %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="{{ page_user_active }}"><a href="{% url 'user' %}">User</a></li>
                    <li class="{{ page_aktivitas_active }}"><a href="{% url 'aktivitas' %}">Aktivitas</a></li>
                  </ul>
                </li>
                  {% endif %}

                {% endif %}
              </ul>

              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                  </ul>
                </li>
                {% else %}
                    <li class="{{ page_login_active }}"><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        {% endblock %}

        <div class="container">
        {% block content %}

        {% endblock %}
        </div>


        <div class="container">
        {% block footer %}
        <div class="col-md-8">
            <footer class="footer navbar-bottom">
              <div class="container text-center">
                <p class="text-muted">&copy; Fasilkom UI</p>
              </div>
            </footer>
        </div>
        {% endblock%}
        </div>

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block js %} {% endblock %}
    </body>
</html>